version: "3.8"

services:
  wordpress:
    image: wordpress:5.8
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: ci40190_kogda
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
    networks:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ci40190_kogda
      MYSQL_USER: root
      MYSQL_PASSWORD: airon2931
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
