version: "3.8"

services:
  wordpress:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ci40190_kogda
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
