services:
  wordpress:
    container_name: wp-cas_wordpress
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - backend
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mysql:5.7
    container_name: wp-cas_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ci40190_kogda
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
